// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg
{
    [FronteggResourceType("frontegg:index/permissionCategory:PermissionCategory")]
    public partial class PermissionCategory : Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp at which the permission category was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// A human-readable description of the permission category.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// A human-readable name for the permission category.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a PermissionCategory resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PermissionCategory(string name, PermissionCategoryArgs args, CustomResourceOptions? options = null)
            : base("frontegg:index/permissionCategory:PermissionCategory", name, args ?? new PermissionCategoryArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PermissionCategory(string name, Input<string> id, PermissionCategoryState? state = null, CustomResourceOptions? options = null)
            : base("frontegg:index/permissionCategory:PermissionCategory", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/okera/pulumi-frontegg/releases/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PermissionCategory resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PermissionCategory Get(string name, Input<string> id, PermissionCategoryState? state = null, CustomResourceOptions? options = null)
        {
            return new PermissionCategory(name, id, state, options);
        }
    }

    public sealed class PermissionCategoryArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// A human-readable description of the permission category.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// A human-readable name for the permission category.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public PermissionCategoryArgs()
        {
        }
    }

    public sealed class PermissionCategoryState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The timestamp at which the permission category was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// A human-readable description of the permission category.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// A human-readable name for the permission category.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public PermissionCategoryState()
        {
        }
    }
}
