// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg
{
    [FronteggResourceType("frontegg:index/role:Role")]
    public partial class Role : Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp at which the role was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Whether the role should be applied to new users by default.
        /// </summary>
        [Output("default")]
        public Output<bool> Default { get; private set; } = null!;

        /// <summary>
        /// A human-readable description of the role.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// A human-readable identifier for the role.
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// The level of the role in the role hierarchy.
        /// </summary>
        [Output("level")]
        public Output<int> Level { get; private set; } = null!;

        /// <summary>
        /// A human-readable name for the role.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The IDs of the permissions that the role confers to its members.
        /// </summary>
        [Output("permissionIds")]
        public Output<ImmutableArray<string>> PermissionIds { get; private set; } = null!;

        /// <summary>
        /// The ID of the tenant that owns the role.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;

        /// <summary>
        /// The ID of the vendor that owns the role.
        /// </summary>
        [Output("vendorId")]
        public Output<string> VendorId { get; private set; } = null!;


        /// <summary>
        /// Create a Role resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Role(string name, RoleArgs args, CustomResourceOptions? options = null)
            : base("frontegg:index/role:Role", name, args ?? new RoleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Role(string name, Input<string> id, RoleState? state = null, CustomResourceOptions? options = null)
            : base("frontegg:index/role:Role", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/okera/pulumi-frontegg/releases/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Role resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Role Get(string name, Input<string> id, RoleState? state = null, CustomResourceOptions? options = null)
        {
            return new Role(name, id, state, options);
        }
    }

    public sealed class RoleArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the role should be applied to new users by default.
        /// </summary>
        [Input("default", required: true)]
        public Input<bool> Default { get; set; } = null!;

        /// <summary>
        /// A human-readable description of the role.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// A human-readable identifier for the role.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The level of the role in the role hierarchy.
        /// </summary>
        [Input("level", required: true)]
        public Input<int> Level { get; set; } = null!;

        /// <summary>
        /// A human-readable name for the role.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("permissionIds", required: true)]
        private InputList<string>? _permissionIds;

        /// <summary>
        /// The IDs of the permissions that the role confers to its members.
        /// </summary>
        public InputList<string> PermissionIds
        {
            get => _permissionIds ?? (_permissionIds = new InputList<string>());
            set => _permissionIds = value;
        }

        public RoleArgs()
        {
        }
    }

    public sealed class RoleState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The timestamp at which the role was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Whether the role should be applied to new users by default.
        /// </summary>
        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// A human-readable description of the role.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// A human-readable identifier for the role.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The level of the role in the role hierarchy.
        /// </summary>
        [Input("level")]
        public Input<int>? Level { get; set; }

        /// <summary>
        /// A human-readable name for the role.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("permissionIds")]
        private InputList<string>? _permissionIds;

        /// <summary>
        /// The IDs of the permissions that the role confers to its members.
        /// </summary>
        public InputList<string> PermissionIds
        {
            get => _permissionIds ?? (_permissionIds = new InputList<string>());
            set => _permissionIds = value;
        }

        /// <summary>
        /// The ID of the tenant that owns the role.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// The ID of the vendor that owns the role.
        /// </summary>
        [Input("vendorId")]
        public Input<string>? VendorId { get; set; }

        public RoleState()
        {
        }
    }
}
