// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceAuthPolicy
    {
        public readonly bool AllowSignups;
        public readonly bool AllowUnverifiedUsers;
        public readonly bool EnableApiTokens;
        public readonly bool EnableRoles;
        public readonly int JwtAccessTokenExpiration;
        public readonly string? JwtAlgorithm;
        public readonly string? JwtPublicKey;
        public readonly int JwtRefreshTokenExpiration;
        public readonly string SameSiteCookiePolicy;

        [OutputConstructor]
        private WorkspaceAuthPolicy(
            bool allowSignups,

            bool allowUnverifiedUsers,

            bool enableApiTokens,

            bool enableRoles,

            int jwtAccessTokenExpiration,

            string? jwtAlgorithm,

            string? jwtPublicKey,

            int jwtRefreshTokenExpiration,

            string sameSiteCookiePolicy)
        {
            AllowSignups = allowSignups;
            AllowUnverifiedUsers = allowUnverifiedUsers;
            EnableApiTokens = enableApiTokens;
            EnableRoles = enableRoles;
            JwtAccessTokenExpiration = jwtAccessTokenExpiration;
            JwtAlgorithm = jwtAlgorithm;
            JwtPublicKey = jwtPublicKey;
            JwtRefreshTokenExpiration = jwtRefreshTokenExpiration;
            SameSiteCookiePolicy = sameSiteCookiePolicy;
        }
    }
}
