// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceAdminPortal
    {
        public readonly bool EnableAccountSettings;
        public readonly bool EnableApiTokens;
        public readonly bool EnableAuditLogs;
        public readonly bool EnablePersonalApiTokens;
        public readonly bool EnablePrivacy;
        public readonly bool EnableProfile;
        public readonly bool EnableRoles;
        public readonly bool EnableSecurity;
        public readonly bool EnableSso;
        public readonly bool EnableSubscriptions;
        public readonly bool EnableUsage;
        public readonly bool EnableUsers;
        public readonly bool EnableWebhooks;
        public readonly Outputs.WorkspaceAdminPortalPalette Palette;

        [OutputConstructor]
        private WorkspaceAdminPortal(
            bool enableAccountSettings,

            bool enableApiTokens,

            bool enableAuditLogs,

            bool enablePersonalApiTokens,

            bool enablePrivacy,

            bool enableProfile,

            bool enableRoles,

            bool enableSecurity,

            bool enableSso,

            bool enableSubscriptions,

            bool enableUsage,

            bool enableUsers,

            bool enableWebhooks,

            Outputs.WorkspaceAdminPortalPalette palette)
        {
            EnableAccountSettings = enableAccountSettings;
            EnableApiTokens = enableApiTokens;
            EnableAuditLogs = enableAuditLogs;
            EnablePersonalApiTokens = enablePersonalApiTokens;
            EnablePrivacy = enablePrivacy;
            EnableProfile = enableProfile;
            EnableRoles = enableRoles;
            EnableSecurity = enableSecurity;
            EnableSso = enableSso;
            EnableSubscriptions = enableSubscriptions;
            EnableUsage = enableUsage;
            EnableUsers = enableUsers;
            EnableWebhooks = enableWebhooks;
            Palette = palette;
        }
    }
}
