// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceCaptchaPolicy
    {
        public readonly ImmutableArray<string> IgnoredEmails;
        public readonly double MinScore;
        public readonly string SecretKey;
        public readonly string SiteKey;

        [OutputConstructor]
        private WorkspaceCaptchaPolicy(
            ImmutableArray<string> ignoredEmails,

            double minScore,

            string secretKey,

            string siteKey)
        {
            IgnoredEmails = ignoredEmails;
            MinScore = minScore;
            SecretKey = secretKey;
            SiteKey = siteKey;
        }
    }
}
