// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceUserActivationEmail
    {
        public readonly string FromAddress;
        public readonly string FromName;
        public readonly string HtmlTemplate;
        public readonly string? RedirectUrl;
        public readonly string Subject;

        [OutputConstructor]
        private WorkspaceUserActivationEmail(
            string fromAddress,

            string fromName,

            string htmlTemplate,

            string? redirectUrl,

            string subject)
        {
            FromAddress = fromAddress;
            FromName = fromName;
            HtmlTemplate = htmlTemplate;
            RedirectUrl = redirectUrl;
            Subject = subject;
        }
    }
}
