// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceGithubSocialLogin
    {
        public readonly string ClientId;
        public readonly string RedirectUrl;
        public readonly string Secret;

        [OutputConstructor]
        private WorkspaceGithubSocialLogin(
            string clientId,

            string redirectUrl,

            string secret)
        {
            ClientId = clientId;
            RedirectUrl = redirectUrl;
            Secret = secret;
        }
    }
}
