// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspacePasswordPolicy
    {
        public readonly bool AllowPassphrases;
        public readonly int History;
        public readonly int MaxLength;
        public readonly int MinLength;
        public readonly int MinPhraseLength;
        public readonly int MinTests;

        [OutputConstructor]
        private WorkspacePasswordPolicy(
            bool allowPassphrases,

            int history,

            int maxLength,

            int minLength,

            int minPhraseLength,

            int minTests)
        {
            AllowPassphrases = allowPassphrases;
            History = history;
            MaxLength = maxLength;
            MinLength = minLength;
            MinPhraseLength = minPhraseLength;
            MinTests = minTests;
        }
    }
}
