// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package frontegg

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupPermission(ctx *pulumi.Context, args *LookupPermissionArgs, opts ...pulumi.InvokeOption) (*LookupPermissionResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupPermissionResult
	err := ctx.Invoke("frontegg:index/getPermission:getPermission", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPermission.
type LookupPermissionArgs struct {
	Key string `pulumi:"key"`
}

// A collection of values returned by getPermission.
type LookupPermissionResult struct {
	CategoryId  string `pulumi:"categoryId"`
	CreatedAt   string `pulumi:"createdAt"`
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Key  string `pulumi:"key"`
	Name string `pulumi:"name"`
}

func LookupPermissionOutput(ctx *pulumi.Context, args LookupPermissionOutputArgs, opts ...pulumi.InvokeOption) LookupPermissionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupPermissionResult, error) {
			args := v.(LookupPermissionArgs)
			r, err := LookupPermission(ctx, &args, opts...)
			return *r, err
		}).(LookupPermissionResultOutput)
}

// A collection of arguments for invoking getPermission.
type LookupPermissionOutputArgs struct {
	Key pulumi.StringInput `pulumi:"key"`
}

func (LookupPermissionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPermissionArgs)(nil)).Elem()
}

// A collection of values returned by getPermission.
type LookupPermissionResultOutput struct{ *pulumi.OutputState }

func (LookupPermissionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPermissionResult)(nil)).Elem()
}

func (o LookupPermissionResultOutput) ToLookupPermissionResultOutput() LookupPermissionResultOutput {
	return o
}

func (o LookupPermissionResultOutput) ToLookupPermissionResultOutputWithContext(ctx context.Context) LookupPermissionResultOutput {
	return o
}

func (o LookupPermissionResultOutput) CategoryId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.CategoryId }).(pulumi.StringOutput)
}

func (o LookupPermissionResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupPermissionResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupPermissionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupPermissionResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.Key }).(pulumi.StringOutput)
}

func (o LookupPermissionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPermissionResultOutput{})
}
