// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface WorkspaceAdminPortal {
    enableAccountSettings: pulumi.Input<boolean>;
    enableApiTokens: pulumi.Input<boolean>;
    enableAuditLogs: pulumi.Input<boolean>;
    enablePersonalApiTokens: pulumi.Input<boolean>;
    enablePrivacy: pulumi.Input<boolean>;
    enableProfile: pulumi.Input<boolean>;
    enableRoles: pulumi.Input<boolean>;
    enableSecurity: pulumi.Input<boolean>;
    enableSso: pulumi.Input<boolean>;
    enableSubscriptions: pulumi.Input<boolean>;
    enableUsage: pulumi.Input<boolean>;
    enableUsers: pulumi.Input<boolean>;
    enableWebhooks: pulumi.Input<boolean>;
    palette: pulumi.Input<inputs.WorkspaceAdminPortalPalette>;
}

export interface WorkspaceAdminPortalPalette {
    error: pulumi.Input<string>;
    info: pulumi.Input<string>;
    primary: pulumi.Input<string>;
    primaryText: pulumi.Input<string>;
    secondary: pulumi.Input<string>;
    secondaryText: pulumi.Input<string>;
    success: pulumi.Input<string>;
    warning: pulumi.Input<string>;
}

export interface WorkspaceAuthPolicy {
    allowSignups: pulumi.Input<boolean>;
    allowUnverifiedUsers: pulumi.Input<boolean>;
    enableApiTokens: pulumi.Input<boolean>;
    enableRoles: pulumi.Input<boolean>;
    jwtAccessTokenExpiration: pulumi.Input<number>;
    jwtAlgorithm?: pulumi.Input<string>;
    jwtPublicKey?: pulumi.Input<string>;
    jwtRefreshTokenExpiration: pulumi.Input<number>;
    sameSiteCookiePolicy: pulumi.Input<string>;
}

export interface WorkspaceCaptchaPolicy {
    ignoredEmails?: pulumi.Input<pulumi.Input<string>[]>;
    minScore: pulumi.Input<number>;
    secretKey: pulumi.Input<string>;
    siteKey: pulumi.Input<string>;
}

export interface WorkspaceFacebookSocialLogin {
    clientId: pulumi.Input<string>;
    redirectUrl: pulumi.Input<string>;
    secret: pulumi.Input<string>;
}

export interface WorkspaceGithubSocialLogin {
    clientId: pulumi.Input<string>;
    redirectUrl: pulumi.Input<string>;
    secret: pulumi.Input<string>;
}

export interface WorkspaceGoogleSocialLogin {
    clientId: pulumi.Input<string>;
    redirectUrl: pulumi.Input<string>;
    secret: pulumi.Input<string>;
}

export interface WorkspaceHostedLogin {
    allowedRedirectUrls?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface WorkspaceLockoutPolicy {
    maxAttempts: pulumi.Input<number>;
}

export interface WorkspaceMfaAuthenticationApp {
    serviceName: pulumi.Input<string>;
}

export interface WorkspaceMfaPolicy {
    allowRememberDevice: pulumi.Input<boolean>;
    deviceExpiration: pulumi.Input<number>;
    enforce: pulumi.Input<string>;
}

export interface WorkspaceMicrosoftSocialLogin {
    clientId: pulumi.Input<string>;
    redirectUrl: pulumi.Input<string>;
    secret: pulumi.Input<string>;
}

export interface WorkspacePasswordPolicy {
    allowPassphrases: pulumi.Input<boolean>;
    history: pulumi.Input<number>;
    maxLength: pulumi.Input<number>;
    minLength: pulumi.Input<number>;
    minPhraseLength: pulumi.Input<number>;
    minTests: pulumi.Input<number>;
}

export interface WorkspacePwnedPasswordEmail {
    fromAddress: pulumi.Input<string>;
    fromName: pulumi.Input<string>;
    htmlTemplate: pulumi.Input<string>;
    redirectUrl?: pulumi.Input<string>;
    subject: pulumi.Input<string>;
}

export interface WorkspaceResetPasswordEmail {
    fromAddress: pulumi.Input<string>;
    fromName: pulumi.Input<string>;
    htmlTemplate: pulumi.Input<string>;
    redirectUrl?: pulumi.Input<string>;
    subject: pulumi.Input<string>;
}

export interface WorkspaceSaml {
    acsUrl: pulumi.Input<string>;
    spEntityId: pulumi.Input<string>;
}

export interface WorkspaceUserActivationEmail {
    fromAddress: pulumi.Input<string>;
    fromName: pulumi.Input<string>;
    htmlTemplate: pulumi.Input<string>;
    redirectUrl?: pulumi.Input<string>;
    subject: pulumi.Input<string>;
}

export interface WorkspaceUserInvitationEmail {
    fromAddress: pulumi.Input<string>;
    fromName: pulumi.Input<string>;
    htmlTemplate: pulumi.Input<string>;
    redirectUrl?: pulumi.Input<string>;
    subject: pulumi.Input<string>;
}
