// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface WorkspaceAdminPortal {
    enableAccountSettings: boolean;
    enableApiTokens: boolean;
    enableAuditLogs: boolean;
    enablePersonalApiTokens: boolean;
    enablePrivacy: boolean;
    enableProfile: boolean;
    enableRoles: boolean;
    enableSecurity: boolean;
    enableSso: boolean;
    enableSubscriptions: boolean;
    enableUsage: boolean;
    enableUsers: boolean;
    enableWebhooks: boolean;
    palette: outputs.WorkspaceAdminPortalPalette;
}

export interface WorkspaceAdminPortalPalette {
    error: string;
    info: string;
    primary: string;
    primaryText: string;
    secondary: string;
    secondaryText: string;
    success: string;
    warning: string;
}

export interface WorkspaceAuthPolicy {
    allowSignups: boolean;
    allowUnverifiedUsers: boolean;
    enableApiTokens: boolean;
    enableRoles: boolean;
    jwtAccessTokenExpiration: number;
    jwtAlgorithm?: string;
    jwtPublicKey: string;
    jwtRefreshTokenExpiration: number;
    sameSiteCookiePolicy: string;
}

export interface WorkspaceCaptchaPolicy {
    ignoredEmails?: string[];
    minScore: number;
    secretKey: string;
    siteKey: string;
}

export interface WorkspaceFacebookSocialLogin {
    clientId: string;
    redirectUrl: string;
    secret: string;
}

export interface WorkspaceGithubSocialLogin {
    clientId: string;
    redirectUrl: string;
    secret: string;
}

export interface WorkspaceGoogleSocialLogin {
    clientId: string;
    redirectUrl: string;
    secret: string;
}

export interface WorkspaceHostedLogin {
    allowedRedirectUrls?: string[];
}

export interface WorkspaceLockoutPolicy {
    maxAttempts: number;
}

export interface WorkspaceMfaAuthenticationApp {
    serviceName: string;
}

export interface WorkspaceMfaPolicy {
    allowRememberDevice: boolean;
    deviceExpiration: number;
    enforce: string;
}

export interface WorkspaceMicrosoftSocialLogin {
    clientId: string;
    redirectUrl: string;
    secret: string;
}

export interface WorkspacePasswordPolicy {
    allowPassphrases: boolean;
    history: number;
    maxLength: number;
    minLength: number;
    minPhraseLength: number;
    minTests: number;
}

export interface WorkspacePwnedPasswordEmail {
    fromAddress: string;
    fromName: string;
    htmlTemplate: string;
    redirectUrl?: string;
    subject: string;
}

export interface WorkspaceResetPasswordEmail {
    fromAddress: string;
    fromName: string;
    htmlTemplate: string;
    redirectUrl?: string;
    subject: string;
}

export interface WorkspaceSaml {
    acsUrl: string;
    spEntityId: string;
}

export interface WorkspaceUserActivationEmail {
    fromAddress: string;
    fromName: string;
    htmlTemplate: string;
    redirectUrl?: string;
    subject: string;
}

export interface WorkspaceUserInvitationEmail {
    fromAddress: string;
    fromName: string;
    htmlTemplate: string;
    redirectUrl?: string;
    subject: string;
}

