// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceAdminPortalArgs : Pulumi.ResourceArgs
    {
        [Input("enableAccountSettings", required: true)]
        public Input<bool> EnableAccountSettings { get; set; } = null!;

        [Input("enableApiTokens", required: true)]
        public Input<bool> EnableApiTokens { get; set; } = null!;

        [Input("enableAuditLogs", required: true)]
        public Input<bool> EnableAuditLogs { get; set; } = null!;

        [Input("enablePersonalApiTokens", required: true)]
        public Input<bool> EnablePersonalApiTokens { get; set; } = null!;

        [Input("enablePrivacy", required: true)]
        public Input<bool> EnablePrivacy { get; set; } = null!;

        [Input("enableProfile", required: true)]
        public Input<bool> EnableProfile { get; set; } = null!;

        [Input("enableRoles", required: true)]
        public Input<bool> EnableRoles { get; set; } = null!;

        [Input("enableSecurity", required: true)]
        public Input<bool> EnableSecurity { get; set; } = null!;

        [Input("enableSso", required: true)]
        public Input<bool> EnableSso { get; set; } = null!;

        [Input("enableSubscriptions", required: true)]
        public Input<bool> EnableSubscriptions { get; set; } = null!;

        [Input("enableUsage", required: true)]
        public Input<bool> EnableUsage { get; set; } = null!;

        [Input("enableUsers", required: true)]
        public Input<bool> EnableUsers { get; set; } = null!;

        [Input("enableWebhooks", required: true)]
        public Input<bool> EnableWebhooks { get; set; } = null!;

        [Input("palette", required: true)]
        public Input<Inputs.WorkspaceAdminPortalPaletteArgs> Palette { get; set; } = null!;

        public WorkspaceAdminPortalArgs()
        {
        }
    }
}
