// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceCaptchaPolicyGetArgs : Pulumi.ResourceArgs
    {
        [Input("ignoredEmails")]
        private InputList<string>? _ignoredEmails;
        public InputList<string> IgnoredEmails
        {
            get => _ignoredEmails ?? (_ignoredEmails = new InputList<string>());
            set => _ignoredEmails = value;
        }

        [Input("minScore", required: true)]
        public Input<double> MinScore { get; set; } = null!;

        [Input("secretKey", required: true)]
        public Input<string> SecretKey { get; set; } = null!;

        [Input("siteKey", required: true)]
        public Input<string> SiteKey { get; set; } = null!;

        public WorkspaceCaptchaPolicyGetArgs()
        {
        }
    }
}
