// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceMfaPolicyArgs : Pulumi.ResourceArgs
    {
        [Input("allowRememberDevice", required: true)]
        public Input<bool> AllowRememberDevice { get; set; } = null!;

        [Input("deviceExpiration", required: true)]
        public Input<int> DeviceExpiration { get; set; } = null!;

        [Input("enforce", required: true)]
        public Input<string> Enforce { get; set; } = null!;

        public WorkspaceMfaPolicyArgs()
        {
        }
    }
}
