// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceAdminPortalPaletteArgs : Pulumi.ResourceArgs
    {
        [Input("error", required: true)]
        public Input<string> Error { get; set; } = null!;

        [Input("info", required: true)]
        public Input<string> Info { get; set; } = null!;

        [Input("primary", required: true)]
        public Input<string> Primary { get; set; } = null!;

        [Input("primaryText", required: true)]
        public Input<string> PrimaryText { get; set; } = null!;

        [Input("secondary", required: true)]
        public Input<string> Secondary { get; set; } = null!;

        [Input("secondaryText", required: true)]
        public Input<string> SecondaryText { get; set; } = null!;

        [Input("success", required: true)]
        public Input<string> Success { get; set; } = null!;

        [Input("warning", required: true)]
        public Input<string> Warning { get; set; } = null!;

        public WorkspaceAdminPortalPaletteArgs()
        {
        }
    }
}
