// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspacePasswordPolicyArgs : Pulumi.ResourceArgs
    {
        [Input("allowPassphrases", required: true)]
        public Input<bool> AllowPassphrases { get; set; } = null!;

        [Input("history", required: true)]
        public Input<int> History { get; set; } = null!;

        [Input("maxLength", required: true)]
        public Input<int> MaxLength { get; set; } = null!;

        [Input("minLength", required: true)]
        public Input<int> MinLength { get; set; } = null!;

        [Input("minPhraseLength", required: true)]
        public Input<int> MinPhraseLength { get; set; } = null!;

        [Input("minTests", required: true)]
        public Input<int> MinTests { get; set; } = null!;

        public WorkspacePasswordPolicyArgs()
        {
        }
    }
}
