// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PermissionCategory extends pulumi.CustomResource {
    /**
     * Get an existing PermissionCategory resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PermissionCategoryState, opts?: pulumi.CustomResourceOptions): PermissionCategory {
        return new PermissionCategory(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'frontegg:index/permissionCategory:PermissionCategory';

    /**
     * Returns true if the given object is an instance of PermissionCategory.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PermissionCategory {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PermissionCategory.__pulumiType;
    }

    /**
     * The timestamp at which the permission category was created.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * A human-readable description of the permission category.
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * A human-readable name for the permission category.
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a PermissionCategory resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PermissionCategoryArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PermissionCategoryArgs | PermissionCategoryState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PermissionCategoryState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as PermissionCategoryArgs | undefined;
            if ((!args || args.description === undefined) && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PermissionCategory.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PermissionCategory resources.
 */
export interface PermissionCategoryState {
    /**
     * The timestamp at which the permission category was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * A human-readable description of the permission category.
     */
    description?: pulumi.Input<string>;
    /**
     * A human-readable name for the permission category.
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PermissionCategory resource.
 */
export interface PermissionCategoryArgs {
    /**
     * A human-readable description of the permission category.
     */
    description: pulumi.Input<string>;
    /**
     * A human-readable name for the permission category.
     */
    name?: pulumi.Input<string>;
}
