// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the frontegg package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'frontegg';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }

    /**
     * The Frontegg api url. Override to change region. Defaults to EU url.
     */
    public readonly apiBaseUrl!: pulumi.Output<string | undefined>;
    /**
     * The client ID for a Frontegg portal API key.
     */
    public readonly clientId!: pulumi.Output<string>;
    /**
     * The Frontegg portal url. Override to change region. Defaults to EU url.
     */
    public readonly portalBaseUrl!: pulumi.Output<string | undefined>;
    /**
     * The corresponding secret key for the API key.
     */
    public readonly secretKey!: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.clientId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if ((!args || args.secretKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'secretKey'");
            }
            resourceInputs["apiBaseUrl"] = args ? args.apiBaseUrl : undefined;
            resourceInputs["clientId"] = args ? args.clientId : undefined;
            resourceInputs["portalBaseUrl"] = args ? args.portalBaseUrl : undefined;
            resourceInputs["secretKey"] = args ? args.secretKey : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * The Frontegg api url. Override to change region. Defaults to EU url.
     */
    apiBaseUrl?: pulumi.Input<string>;
    /**
     * The client ID for a Frontegg portal API key.
     */
    clientId: pulumi.Input<string>;
    /**
     * The Frontegg portal url. Override to change region. Defaults to EU url.
     */
    portalBaseUrl?: pulumi.Input<string>;
    /**
     * The corresponding secret key for the API key.
     */
    secretKey: pulumi.Input<string>;
}
